import type { Metadata } from "next";
import { Inter, Jockey_One } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Inter({ subsets: ["latin"] });
const jockey = Jockey_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-jockey",
});

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jockey.className}>{children}</body>
    </html>
  );
}
